version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes: 
        - ./minio_storage:/data
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always